dashboard/result/urls.py
from django.urls import path

app_name = 'result_dashboard'

from . import views

urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('release/', views.ReleaseResult.as_view(), name='release_result'),
    path('check/', views.CheckResult.as_view(), name='check_result'),
    path('student/<int:pk>/', views.StudentResultView.as_view(), name='student_result_view'),
    #Grade
    path('grade/add/', views.CreateGrade.as_view(), name='add_grade'),
    path('grade/<int:pk>/', views.UpdateGrade.as_view(), name='update_grade'),
    path('grade/<int:pk>/delete/', views.DeleteGrade.as_view(), name='delete_grade'),
    #CA
    path('module/<module_id>/ca/<ca_id>/result/', views.ModuleCAResult.as_view(), name='module_ca_result'),
    path('student/ca/mark/<int:pk>', views.MarkStudentCA.as_view(), name='mark_student_ca'),
    #Exam
    path('course/<course_id>/exam/<exam_id>/result/', views.CourseExamResult.as_view(), name='course_exam_result'),
    path('student/exam/mark/<int:pk>', views.MarkStudentExam.as_view(), name='mark_student_exam'),
]

exam/urls.py
from django.urls import path

app_name = 'exam'

from . import views

urlpatterns = [
    path('ca/<ca_id>/take/module/<module_id>/paper/<paper_model>/<int:pk>', views.TakeCA.as_view(), name='take_ca'),
    path('<exam_id>/take/course/<course_id>/paper/<paper_model>/<int:pk>/', views.TakeExam.as_view(), name='take_exam'),
    path('course/<course_id>/', views.CourseExamIndex.as_view(), name='course_exam_index'),
]

oelern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve 

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    path('', include('custom_auth.urls')),
    path('django-admin/', admin.site.urls),
    path('auth/', include("django.contrib.auth.urls")),
    path('course/', include('course.urls')),
    path('register/', include('student_reg.urls')),
    path('student/', include('student.urls')),
    path('payment/', include('payment.urls')),
    path('academic/', include('academic.urls')),
    path("paystack/", include(('paystack.urls', 'paystack'),namespace='paystack')),
    path('exam/', include('exam.urls')),
    path('product/', include('product.urls')),
    path('result/', include('result.urls')),
    path('certificate/', include('certificate.urls')),

    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teacher/', include('dashboard.teacher.urls')),
    path('dashboard/course/', include('dashboard.course.urls')),
    path('dashboard/product/', include('dashboard.product.urls')),
    path('dashboard/account/', include('dashboard.custom_auth.urls')),
    path('dashboard/result/', include('dashboard.result.urls')),
    path('dashboard/exam/', include('dashboard.exam.urls')),
    path('dashboard/certificate/', include('dashboard.certificate.urls')),
    path('dashboard/academic/', include('dashboard.academic.urls')),
    path('dashboard/student/', include('dashboard.student.urls')),
    
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

paystack/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

result/urls.py
from django.urls import path

app_name = 'result'

from . import views

urlpatterns = [
    path('check/', views.CheckResult.as_view(), name='check_result'),
    path('student/<int:pk>/', views.StudentResultView.as_view(), name='student_result_view'),
    path('verify/', views.VerifyResult.as_view(), name='verify_result'),
    path('verify/student/<int:pk>/', views.VerifyResultView.as_view(), name='verify_result_view'),
]

dashboard/academic/models.py
from django.db import models

# Create your models here.

dashboard/certificate/models.py
from django.db import models

# Create your models here.

dashboard/certificate/forms.py
from django import forms
from django import forms

from academic.models import Batch
from course.models import Course
from dashboard.result.utils import is_result_released

class GetCourseCertificateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        return super().__init__(*args, **kwargs)

    batch = forms.ModelChoiceField(queryset=Batch.objects.all())
    course = forms.ModelChoiceField(queryset=Course.objects.all())
    
    def clean_batch(self):
        batch = self.cleaned_data.get('batch')
        if not is_result_released(batch):
            raise forms.ValidationError('Released result for selected Batch is not found')
        return batch

dashboard/course/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from djangoformsetjs.utils import formset_media_js

from course.models import Course, Module

class BaseFormSetForm(forms.ModelForm):
    class Media(object):
        js = formset_media_js 

ModuleFormSet = inlineformset_factory(Course, Module, form=BaseFormSetForm, fields=['title', 'sub_title', 'order', 'live', 'description'], extra=1, can_delete=True)

dashboard/teacher/forms.py
from django import forms
from intl_tel_input.widgets import IntlTelInputWidget

from teacher.models import Teacher

class TeacherForm(forms.ModelForm):
    teacher_in_form = forms.BooleanField(widget=forms.HiddenInput, initial=True)

    class Meta:
        model = Teacher
        fields = ['phone_number', 'address', 'lga_of_origin', 'state_of_origin', 'nationality', 'passport']
        widgets = {
            #'date_of_birth': forms.SelectDateWidget()
            'phone_number': IntlTelInputWidget(preferred_countries=['ng'],default_code='ng'),
        }

dashboard/academic/views.py
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy
from django.contrib import messages

from course.models import Course
from .tables import BatchTable
from django_tables2 import SingleTableView
from django.views.generic.base import TemplateView, View

from academic.models import Batch
from dashboard.result.utils import BATCH, is_result_released

class Dashboard(LoginRequiredMixin, PermissionRequiredMixin, SingleTableView):
    permission_required = 'admin'
    template_name = 'dashboard/academic/dashboard.html'
    table_class = BatchTable
    model = Batch

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            batch = Batch.objects.get(is_current=True)
        except Batch.DoesNotExist: 
            batch = None
        context['current_batch'] = batch
        return context

class GraduateBatch(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = 'admin'
    template_name = 'dashboard/academic/graduate_batch.html'

    def dispatch(self, request, *args, **kwargs):
        redirect_to = reverse('academic_dashboard:dashboard')
        if not is_result_released(BATCH):
            messages.info(request, 'Result must be released for batch to be graduated.')
            return redirect(redirect_to)
        self.current_batch = Batch.objects.get(is_current=True)
        if not self.current_batch.next_batch:
            messages.info(request, 'Current batch must have next batch. Please! set next batch manually')
            return redirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        next_batch = self.current_batch.next_batch
        courses = Course.objects.all()
        for course in courses:
            course.students.clear()
        next_batch.is_current = True
        next_batch.save()
        Batch.objects.exclude(id=next_batch.id).update(is_current=False)
        return redirect(reverse('academic_dashboard:dashboard'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_batch'] = self.current_batch
        context['next_batch'] = self.current_batch.next_batch
        return context

class BatchStatusToggle(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'admin'

    def dispatch(self, request, *args, **kwargs):
        self.batch = Batch.objects.get(is_current=True)
        self.redirect_to = reverse('academic_dashboard:dashboard')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if self.batch.live:
            self.batch.live = False
            self.batch.save()
            messages.info(request, 'Batch successfully closed')
            return redirect(self.redirect_to)
        self.batch.live = True
        self.batch.save()
        messages.success(request, 'Batch successfully Opened')
        return redirect(self.redirect_to)

class CreateBatch(LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'admin'
    model = Batch
    fields = ['name', 'order', 'next_batch', 'description']
    template_name = 'general/general_form.html'
    success_message = 'Batch was added successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add new batch'
        return context

class UpdateBatch(LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'admin'
    model = Batch
    fields = ['name', 'order', 'next_batch', 'description']
    template_name = 'general/general_form.html'
    success_message = 'Batch was updated successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit batch'
        return context

class DeleteBatch(LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'admin'
    model = Batch
    template_name = 'general/general_confirm_delete.html'
    success_url = reverse_lazy('academic_dashboard:dashboard')
    success_message = 'Batch ({}) deleted successfully'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_current:
            messages.error(request, 'Current session can not be deleted')
            return redirect(reverse('academic_dashboard:dashboard'))
        return super().post(request, *args, **kwargs)

dashboard/certificate/views.py
from unittest import result
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic.base import View, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from academic.models import Batch
from certificate.models import Certificate
from course.models import Course
from .forms import GetCourseCertificateForm
from django_tables2 import SingleTableView
from django.views.generic.edit import UpdateView

from dashboard.result.forms import CheckResultForm
from .tables import CourseCerficateTable
from student.models import Student
from result.models import StudentResult

class Dashboard(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = 'admin'
    template_name = 'dashboard/certificate/dashboard.html'
    
class CreateCertificate(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = 'admin'
    template_name = 'dashboard/certificate/form.html'
    form = CheckResultForm

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            student = Student.objects.get(user__email__exact=email)
            batch = form.cleaned_data.get('batch')
            course = form.cleaned_data.get('course')
            student_result = StudentResult.objects.get(student=student, course=course, batch=batch)
            certificate = Certificate.objects.get_or_create(result=student_result)[0]
            return redirect(reverse('certificate_dashboard:update_certificate', kwargs={'pk': certificate.pk}))
        return self.render_to_response({'form': form, 'meta_title':'Create | Certificate','title':'Create certificate','btn_text':'Create'})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form()
        context['meta_title'] = 'Create | Certificate'
        context['title'] = 'Create certificate'
        context['btn_text'] = 'Create'
        return context
    

class GetCertificate(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = 'admin'
    form = CheckResultForm
    template_name = 'dashboard/certificate/form.html'

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            student = Student.objects.get(user__email__exact=email)
            batch = form.cleaned_data.get('batch')
            course = form.cleaned_data.get('course')
            student_result = StudentResult.objects.get(student=student, course=course, batch=batch)
            try:
                certificate = Certificate.objects.get(result=student_result)
                return redirect(reverse('certificate_dashboard:update_certificate', kwargs={'pk': student_result.certificate.pk}))
            except Certificate.DoesNotExist:
                messages.error(request, 'Unable to find certificate, Please! Add certificate to that result first.')
                return redirect(reverse('certificate_dashboard:dashboard'))
        return self.render_to_response({'form': form,'meta_title':'Get | Certificate','title': 'Get Certificate','btn_text': 'Get Certificate'})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form()
        context['meta_title'] = 'Get | Certificate'
        context['title'] = 'Get Certificate'
        context['btn_text'] = 'Get certificate'
        return context        

class UpdateCertificate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'admin'
    model = Certificate
    fields = ['file']
    template_name = 'dashboard/certificate/update_certificate.html'
    
    def get_success_url(self):
        course = self.object.result.course
        batch = self.object.result.batch
        return reverse('certificate_dashboard:course_certificate', kwargs={'course_id': course.id,'batch_id':batch.id})

class GetCourseCertificate(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = 'admin'
    form = GetCourseCertificateForm
    template_name = 'dashboard/certificate/form.html'

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if form.is_valid():
            batch = form.cleaned_data.get('batch')
            course = form.cleaned_data.get('course')
            return redirect(reverse('certificate_dashboard:course_certificate', kwargs={'batch_id':batch.id,'course_id':course.id}))
        return self.render_to_response({'form':form, 'title': 'Get course certificates','btn_text': 'Get certificates',})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form()
        context['meta_title'] = 'Get | Course Cerficate'
        context['title'] = 'Get course certificates'
        context['btn_text'] = 'Get certificates'
        return context
    

class CourseCertificate(LoginRequiredMixin, PermissionRequiredMixin, SingleTableView):
    permission_required = 'admin'
    template_name = 'dashboard/certificate/course_certificate.html'
    table_class = CourseCerficateTable

    def dispatch(self, request, batch_id, course_id, *args, **kwargs):
        self.batch = get_object_or_404(Batch, id=batch_id)
        self.course = get_object_or_404(Course, id=course_id)
        return super().dispatch(request, batch_id, course_id, *args, **kwargs)
    
    def get_queryset(self):
        return Certificate.objects.filter(result__batch=self.batch,result__course=self.course)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = self.course
        context['batch'] = self.batch
        return context
    

templates/dashboard/result/check_result.html
{% extends 'teacher_base.html' %}

{% block title %}
 Result | Check
{% endblock title %}

{% block content %}
  <div class="container">
    {% include 'result/partials/check_result_card.html' %}
  </div>
{% endblock content %}

templates/dashboard/result/dashboard.html
{% extends 'teacher_base.html' %}

{% load django_tables2 %}

{% block title %}
  Result | Dashboard
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="card card-success card-outline">
          <div class="card-header">
            <h3 class="card-header">Result Dashboard</h3>
          </div>
          <div class="card-body">
            <a href="{% url 'result_dashboard:add_grade' %}" class="btn btn-success btn-block">
                <i class="fas fa-plus mr-3">Add new grade</i>
            </a>
            <div class="border border-success shadow p-2 m-2">
              {% if is_result_released %}
                <p>Result has been released!</p>
              {% else %}
                Result is not released!
                <a href="{% url 'result_dashboard:release_result' %}" class="btn btn-success btn-block">
                    <i class="fas fa-compass mr-3">Release result</i>
              {% endif %}
              <a href="{% url 'result_dashboard:check_result' %}" class="btn btn-info btn-block">Check student result</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-9">
        {% render_table table %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/dashboard/result/mark_student_ca.html
{% extends 'teacher_base.html' %}

{% load widget_tweaks %}

{% block title %}
{% if obj.ca %}
 Mark Results | {{ obj.ca }}
{% elif obj.exam %}
  Exam Results | {{ obj.exam }}
{% endif %}
{% endblock title %}

{% block content %}
  <div class="row">
    {% if parent_url %}
    <div class="col-12">
      <a class="btn btn-outline-primary mb-2 btn-lg" href="{{ parent_url }}">
        <i class="fas fa-angle-double-left"></i>
      </a>
    </div>
    {% endif %}
    <div class="col-lg-3">
      <div class="card card-primary card-outline" style="max-width: 550px;">
        <div class="card-header">
          <h3 class="card-title">Mark student {% if obj.ca %} CA {% elif obj.exam %} Exam {% endif %} Result</h3>
        </div>
        <div class="card-body">
          <table class="table">
            <tr>
             <th>Student</th>
             <td>{{ obj.student }}</td>
            </tr>
            {% if obj.ca %}
            <tr>
              <th>CA</th>
              <td>{{ obj.ca }}</td>
             </tr>
            {% endif %}
            {% if obj.exam %}
            <tr>
              <th>CA</th>
              <td>{{ obj.exam }}</td>
             </tr>
            {% endif %}
             <tr>
              <th>Batch</th>
              <td>{{ obj.batch }}</td>
             </tr>
             {% if obj.module %}
             <tr>
              <th>Module</th>
              <td>{{ obj.module }}</td>
             </tr>
             {% endif %}
             <tr>
              <th>Course</th>
              <td>{{ obj.course }}</td>
             </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="col-lg-9">
      <form action="" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        <div class="card card-primary">
          <div class="card-header">
            <h3 class="card-title">Submitted answers</h3>
          </div>
          <div class="card-body">
            <div class="row row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
              {% for form in formset.forms  %}
                <div class="col">
                  <div class="card card-info card-outline">
                    <div class="card-header">
                      <h3 class="card-title">({{ form.instance.question.question_no }}). {{ form.instance.question.question }}</h3>
                    </div>
                    <div class="card-body">
                      {{ form.id }}
                      {% if form.errors %}
                       <div class="alert alert-danger alert-dismissible" role="alert">
                        <button class="close" type="button" data-dismiss="alert" aria-label="close">&#215;</button>
                        {% for error in form.non_field_errors %}
                         {{ error }}{% if not forloop.last %}<br>{% endif %}
                        {% endfor %}
                       </div>
                      {% endif %}
                        <p class="card-text">{{ form.instance.student_answer }}</p><hr>
                      <b>Maximum of: <span class="badge badge-primary">{{ form.instance.question.marks }} marks</span></b>
                      {% render_field form.score class="form-control" %}
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
          <div class="card-footer">
            <input type="submit" value="Submit" class="btn btn-primary btn-lg">
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

templates/dashboard/result/module_ca_result.html
{% extends 'teacher_base.html' %}

{% load django_tables2 %}

{% block title %}
 {% if ca %}
  Module CA Results | {{ ca }}
 {% elif exam %}
  Course Exam Results | {{ exam }}
 {% endif %}
{% endblock title %}

{% block content %}
 <div class="row">
   {% if parent_url %}
   <div class="col-12">
     <a class="btn btn-outline-primary mb-2 btn-lg" href="{{ parent_url }}">
       <i class="fas fa-angle-double-left"></i>
     </a>
   </div>
   {% endif %}
    <div class="col-md-3">
      <div class="card card-primary card-outline">
      <div class="card-header">
        <h2 class="card-title">{{ marked_count }} out of {{ all_count }} {% if ca %} CA {% elif exam %} Exam {% endif %} results are marked</h2>
      </div>
      <div card-body>
        <table class="table">
         <tr>
            <th>Course</th>
            <td>{{ course }}</td>
         </tr>
         {% if module %}
         <tr>
          <th>Module</th>
          <td>{{ module }}</td>
         </tr>
         {% endif %}
         {% if ca %}
         <tr>
          <th>CA</th>
          <td>{{ca }}</td>
         </tr>
         {% endif %}
         {% if exam %}
         <tr>
          <th>CA</th>
          <td>{{ exam }}</td>
         </tr>
         {% endif %}
         <tr>
            <th>Batch</th>
            <td>{{batch }}</td>
         </tr>
        </table>
      </div>
    </div>
   </div>
    <div class="col-md-9">
      {% render_table table %}
    </div>
 </div>
{% endblock content %}

templates/dashboard/result/release_result.html
{% extends 'teacher_base.html' %}

{% block title %}
  Release result | Current samester
{% endblock title %}

{% block content %}
  <div class="card card-primary card-outline" style="max-width: 550px;margin:auto;">
    <div class="card-header">
      <h2 class="card-title">{{ batch }} result is about to be released.</h2>
    </div>
    <div class="card-body">
      <h5 class="card-subtitle">Result release is always accompanied with several changes 
        and restrictions that may not be reversed easiy. Please! Put the following informations 
        into consideration before releasing the batch result.</h5>
      <div class="list-group">
        <div href="#" class="list-group-item">
          <h5>After release, Exams and assessment for this batch with no longer be accessible or considered</h5>
          <p class="mb-1">If there is any assessment or exam that is expected to be taken. Wait!</p>
        </div>
        <div class="list-group-item">
            <h5>Admin or instructor can neither mark nor modify any result</h5>
            <p class="mb-1">If there is any modification or marking, do it before release</p>
        </div>
        <div class="list-group-item">
            <h5>Result for this batch will be generated, released and be accessible to all students even after if this batch is over</h5>
            <p class="mb-1">It is after release that students can access their result</p>
        </div>
        <div class="list-group-item">
            <h5>Only Exams and Assessments that are currently published under course that are currently live will be considered</h5>
            <p class="mb-1">If there is courses, exams, or assessments that you want to be included, just unpublish the</p>
        </div>
        <div class="list-group-item">
            <h5>The result GENERATOR is programmed to generate result by aggregating previously submitted 
                exams and assessments to 70 marks and 30 marks respectively.
            </h5>
            <p class="mb-1"></p>
        </div>
      </div>
      <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Release result" class="btn btn-success btn-lg btn-block">
      </form>
    </div>
  </div>
{% endblock content %}

templates/dashboard/result/student_result_view.html
{% extends 'teacher_base.html' %}

{% block title %}
  Student | Result
{% endblock title %}

{% block content %}
  <div class="container">
    {% include 'result/partials/student_result.html' %}
  </div>
{% endblock  %}