course/urls.py
from django.urls import path

app_name = 'course'

from . import views

urlpatterns = [
    path('', views.EnrollIndex.as_view(), name='enroll_index'),
    path('register', views.NonrollIndex.as_view(), name='nonroll_index'),
    path('module/<int:module_id>', views.CourseDetail.as_view(), name='course_detail'),
]

dashboard/course/urls.py
from django.urls import path

app_name = 'course_dashboard'

from . import views

urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    #Subject
    path('subject/add/', views.CreateSubject.as_view(), name='add_subject'),
    path('subject/<int:pk>/', views.UpdateSubject.as_view(), name='edit_subject'),
    path('subject/<int:pk>/delete/', views.DeleteSubject.as_view(), name='delete_subject'),
    #Course
    path('add/', views.CreateCourse.as_view(), name='add_course'),
    path('<pk>/edit/', views.UpdateCourse.as_view(), name='edit_course'),
    path('<pk>/delete/', views.DeleteCourse.as_view(), name='delete_course'),
    path('add/<course_id>/student/', views.CouseAddStudent.as_view(), name='course_add_student'),
    # Module
    path('<pk>/module/', views.UpdateModule.as_view(), name='edit_module'),
    path('module/<int:module_id>/content/<model_name>/create/', views.CreateUpdateContent.as_view(),name='add_content'),
    path('module/<int:module_id>/content/<model_name>/<id>/', views.CreateUpdateContent.as_view(), name='edit_content'),
    path('content/<int:pk>/delete', views.DeleteContent.as_view(), name='delete_content'),
    path('module/<int:module_id>/', views.ModuleContentList.as_view(), name='content_list'),
    path('content/publish/toggle/<model_name>/<int:pk>/', views.PublishToggle.as_view(), name='publish_toggle'),
]

dashboard/exam/urls.py
from django.urls import path

app_name = 'exam_dashboard'

from . import views

urlpatterns = [
    #CA
    path('module/<int:module_id>/ca/<model_name>/create/', views.CreateUpdateCA.as_view(), name='add_ca'),
    path('module/<int:module_id>/ca/<model_name>/<id>/', views.CreateUpdateCA.as_view(), name='edit_ca'),
    path('module/<int:module_id>/ca/<model_name>/question/<paper_id>/', views.UpdateCAQuestion.as_view(), name='edit_ca_question'),
    path('ca/<int:pk>/delete', views.DeleteCA.as_view(), name='delete_ca'),
    #Exam
    path('course/<int:pk>', views.CourseExam.as_view(), name='course_exam'),
    path('course/<int:course_id>/exam/<model_name>/create/', views.CreateUpdateExam.as_view(), name='add_exam'),
    path('course/<int:course_id>/exam/<model_name>/<id>/', views.CreateUpdateExam.as_view(), name='edit_exam'),
    path('course/<int:course_id>/exam/<model_name>/question/<paper_id>/', views.UpdateExamQuestion.as_view(), name='edit_exam_question'),
    path('exam/<int:pk>/delete', views.DeleteExam.as_view(), name='delete_exam'),
    path('status/toggle/<course_id>/', views.ExamStatusToggle.as_view(), name='exam_status_toggle')
]

dashboard/result/urls.py
from django.urls import path

app_name = 'result_dashboard'

from . import views

urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('release/', views.ReleaseResult.as_view(), name='release_result'),
    path('check/', views.CheckResult.as_view(), name='check_result'),
    path('student/<int:pk>/', views.StudentResultView.as_view(), name='student_result_view'),
    #Grade
    path('grade/add/', views.CreateGrade.as_view(), name='add_grade'),
    path('grade/<int:pk>/', views.UpdateGrade.as_view(), name='update_grade'),
    path('grade/<int:pk>/delete/', views.DeleteGrade.as_view(), name='delete_grade'),
    #CA
    path('module/<module_id>/ca/<ca_id>/result/', views.ModuleCAResult.as_view(), name='module_ca_result'),
    path('student/ca/mark/<int:pk>', views.MarkStudentCA.as_view(), name='mark_student_ca'),
    #Exam
    path('course/<course_id>/exam/<exam_id>/result/', views.CourseExamResult.as_view(), name='course_exam_result'),
    path('student/exam/mark/<int:pk>', views.MarkStudentExam.as_view(), name='mark_student_exam'),
]

exam/urls.py
from django.urls import path

app_name = 'exam'

from . import views

urlpatterns = [
    path('ca/<ca_id>/take/module/<module_id>/paper/<paper_model>/<int:pk>', views.TakeCA.as_view(), name='take_ca'),
    path('<exam_id>/take/course/<course_id>/paper/<paper_model>/<int:pk>/', views.TakeExam.as_view(), name='take_exam'),
    path('course/<course_id>/', views.CourseExamIndex.as_view(), name='course_exam_index'),
]

oelern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve 

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    path('', include('custom_auth.urls')),
    path('django-admin/', admin.site.urls),
    path('auth/', include("django.contrib.auth.urls")),
    path('course/', include('course.urls')),
    path('register/', include('student_reg.urls')),
    path('student/', include('student.urls')),
    path('payment/', include('payment.urls')),
    path('academic/', include('academic.urls')),
    path("paystack/", include(('paystack.urls', 'paystack'),namespace='paystack')),
    path('exam/', include('exam.urls')),
    path('product/', include('product.urls')),
    path('result/', include('result.urls')),
    path('certificate/', include('certificate.urls')),

    path('dashboard/', include('dashboard.urls')),
    path('dashboard/teacher/', include('dashboard.teacher.urls')),
    path('dashboard/course/', include('dashboard.course.urls')),
    path('dashboard/product/', include('dashboard.product.urls')),
    path('dashboard/account/', include('dashboard.custom_auth.urls')),
    path('dashboard/result/', include('dashboard.result.urls')),
    path('dashboard/exam/', include('dashboard.exam.urls')),
    path('dashboard/certificate/', include('dashboard.certificate.urls')),
    path('dashboard/academic/', include('dashboard.academic.urls')),
    path('dashboard/student/', include('dashboard.student.urls')),
    
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

paystack/urls.py
import django

version = django.get_version().split(".")
if int(version[0]) >= 2:
    from django.urls import re_path as url
else:
    from django.conf.urls import url

from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

urlpatterns = [
    url(
        r"^verify-payment/(?P<order>[\w.@+-]+)/$",
        views.verify_payment,
        name="verify_payment",
    ),
    url(
        r"^failed-verification/(?P<order_id>[\w.@+-]+)/$",
        views.failure_redirect_view,
        name="failed_verification",
    ),
    url(
        r"^successful-verification/(?P<order_id>[\w.@+-]+)/$",
        views.success_redirect_view,
        name="successful_verification",
    ),
    url(
        r"^failed-page/$",
        views.TemplateView.as_view(template_name="paystack/failed-page.html"),
        name="failed_page",
    ),
    url(
        r"^success-page/$",
        views.TemplateView.as_view(template_name="paystack/success-page.html"),
        name="success_page",
    ),
    url(r"^webhook/$", csrf_exempt(views.webhook_view), name="webhook"),
]

dashboard/academic/models.py
from django.db import models

# Create your models here.

dashboard/course/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from djangoformsetjs.utils import formset_media_js

from course.models import Course, Module

class BaseFormSetForm(forms.ModelForm):
    class Media(object):
        js = formset_media_js 

ModuleFormSet = inlineformset_factory(Course, Module, form=BaseFormSetForm, fields=['title', 'sub_title', 'order', 'live', 'description'], extra=1, can_delete=True)

course/views.py
from django.shortcuts import render, get_object_or_404, redirect
from  django.views.generic.base import TemplateView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.urls import reverse
from django.contrib import messages

from academic.mixins import CurrentBatchLiveMixin
from dashboard.result.utils import is_result_released

from .models import Course, Module, Video, Image, File, Text, StudentCompletedModule
from student.mixins import StudentTestMixin
from .mixins import StudentCourseMixin
from . import utils
from academic.utils import get_current_batch

BATCH = get_current_batch()

#class LiveCourseMixin():
 #   return self.course.live
    
class EnrollIndex(StudentTestMixin, TemplateView):
    template_name = 'course/enroll_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student = self.request.user.student
        context['student'] = student
        context['courses_enrolled_count'] = student.courses_joined.all().count()
        context['enrolled_courses'] = student.courses_joined.filter(live=True)
        context['is_result_released'] = is_result_released()
        return context
        
class NonrollIndex(StudentTestMixin, TemplateView):
    template_name = 'course/nonroll_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student = self.request.user.student
        context['student'] = student
        context['courses_enrolled_count'] = student.courses_joined.all().count()
        context['non_enrolled_courses'] = Course.objects.filter(live=True, registration_open=True).exclude(students=student)
        return context

class CourseDetail(StudentTestMixin, StudentCourseMixin, CurrentBatchLiveMixin, TemplateView):
    template_name = 'course/course_detail.html'

    def dispatch(self, request, module_id):
        self.module = get_object_or_404(Module, pk=module_id)
        self.course = self.module.course
        self.videos = []
        self.files = []
        self.images = []
        self.texts = []
        redirect_to = reverse('course:enroll_index')
        student = request.user.student
        self.student = student
        self.batch = BATCH
        if not self.module.live:
            messages.info(request, 'The module is currently closed')
            return redirect(redirect_to)
        #return utils.validate_prev_modules(request, student, self.module)
        #course = module.course
        first_module = self.course.modules.order_by('order').first()
        last_module = utils.get_last_finished_module(student, self.course)
        if not last_module is None: 
            last_module = last_module.module
        next_module = utils.get_next_module(student, self.course)
        if last_module is None and self.module != first_module:
            messages.info(request, 'To access module, You must complete its previous ones')
            return redirect(reverse('course:course_detail', kwargs={'module_id': first_module.pk}))
        if self.module != first_module:
            if last_module.order + 1 < self.module.order and self.module != next_module:
                messages.info(request, 'To access module, You must complete its previous ones')
                return redirect(reverse('course:course_detail', kwargs={'module_id': next_module.pk}))
        for content in self.module.contents.filter(live=True):
            if type(content.item) == Video:
                self.videos.append(content.item)
            elif type(content.item) == File:
                self.files.append(content.item)
            elif type(content.item) == Image:
                self.images.append(content.item)
            elif type(content.item) == Text:
                self.texts.append(content.item)
        return super().dispatch(request, module_id)

    def get(self, request, *args, **kwargs):
        clear = StudentCompletedModule.objects.get_or_create(student=self.student, module=self.module, course=self.course, batch=self.batch)[0]
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = self.course
        context['module'] = self.module
        context['assessments'] = self.module.assessments.filter(live=True)
        context['videos'] = self.videos
        context['files'] = self.files
        context['images'] = self.images
        context['texts'] = self.texts
        context['next_module'] = utils.get_next_module_for_module(self.module)
        context['has_next_module'] = utils.has_next_module(self.module)
        context['prev_module'] = utils.get_prev_module_for_module(self.module)
        context['has_prev_module'] = utils.has_prev_module(self.module)
        return context

    #if student does not complete previous module, deny access and redirect to supposed module
    #Student attempt Test ca once
    #module must be opened
    #student must be in course.students

dashboard/academic/views.py
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse, reverse_lazy
from django.contrib import messages

from course.models import Course
from .tables import BatchTable
from django_tables2 import SingleTableView
from django.views.generic.base import TemplateView, View

from academic.models import Batch
from dashboard.result.utils import BATCH, is_result_released

class Dashboard(LoginRequiredMixin, PermissionRequiredMixin, SingleTableView):
    permission_required = 'admin'
    template_name = 'dashboard/academic/dashboard.html'
    table_class = BatchTable
    model = Batch

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            batch = Batch.objects.get(is_current=True)
        except Batch.DoesNotExist: 
            batch = None
        context['current_batch'] = batch
        return context

class GraduateBatch(LoginRequiredMixin, PermissionRequiredMixin, TemplateView):
    permission_required = 'admin'
    template_name = 'dashboard/academic/graduate_batch.html'

    def dispatch(self, request, *args, **kwargs):
        redirect_to = reverse('academic_dashboard:dashboard')
        if not is_result_released(BATCH):
            messages.info(request, 'Result must be released for batch to be graduated.')
            return redirect(redirect_to)
        self.current_batch = Batch.objects.get(is_current=True)
        if not self.current_batch.next_batch:
            messages.info(request, 'Current batch must have next batch. Please! set next batch manually')
            return redirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        next_batch = self.current_batch.next_batch
        courses = Course.objects.all()
        for course in courses:
            course.students.clear()
        next_batch.is_current = True
        next_batch.save()
        Batch.objects.exclude(id=next_batch.id).update(is_current=False)
        return redirect(reverse('academic_dashboard:dashboard'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_batch'] = self.current_batch
        context['next_batch'] = self.current_batch.next_batch
        return context

class BatchStatusToggle(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'admin'

    def dispatch(self, request, *args, **kwargs):
        self.batch = Batch.objects.get(is_current=True)
        self.redirect_to = reverse('academic_dashboard:dashboard')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if self.batch.live:
            self.batch.live = False
            self.batch.save()
            messages.info(request, 'Batch successfully closed')
            return redirect(self.redirect_to)
        self.batch.live = True
        self.batch.save()
        messages.success(request, 'Batch successfully Opened')
        return redirect(self.redirect_to)

class CreateBatch(LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'admin'
    model = Batch
    fields = ['name', 'order', 'next_batch', 'description']
    template_name = 'general/general_form.html'
    success_message = 'Batch was added successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add new batch'
        return context

class UpdateBatch(LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'admin'
    model = Batch
    fields = ['name', 'order', 'next_batch', 'description']
    template_name = 'general/general_form.html'
    success_message = 'Batch was updated successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit batch'
        return context

class DeleteBatch(LoginRequiredMixin, SuccessMessageMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'admin'
    model = Batch
    template_name = 'general/general_confirm_delete.html'
    success_url = reverse_lazy('academic_dashboard:dashboard')
    success_message = 'Batch ({}) deleted successfully'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_current:
            messages.error(request, 'Current session can not be deleted')
            return redirect(reverse('academic_dashboard:dashboard'))
        return super().post(request, *args, **kwargs)

templates/dashboard/course/content_list.html
{% extends 'teacher_base.html' %}

{% load course_dashboard %}

{% block title %}
Course | Module Contents
{% endblock %}

{% block content %}
 <div class="row">
   <div class="col-12">
     <div class="d-flex justify-content-between">
      <a class="btn btn-outline-primary mb-2 btn-lg" href="{% url 'course_dashboard:dashboard' %}">
        <i class="fas fa-angle-double-left"></i> </a>
        <h2>{{ course.title }}</h2>
     </div>
   </div>
   <div class="col-md-3">
     <ul class="list-group">
       {% for nav_module in course.modules.all %}
         <a href="{% url 'course_dashboard:content_list' nav_module.id %}" class="list-group-item list-group-item-group {% if nav_module == module %} active {% endif %}">
           {{ nav_module.sub_title }}<span class="badge bg-success">{{ nav_module.num_contents }}</span>
         </a>
       {% endfor %}
     </ul>
   </div>
   <div class="col-md-9">
     <div class="card card-success card-outline">
       <div class="card-header">
         <h2 class="card-title">{{ module.title }}<span class="float-right badge bg-primary">{{ module.sub_title }}</span></h2>
       </div>
       <div class="card-body">
         <div class="row">
           <div class="col-md-6">
             <div class="border border-dark shadow rounded p-2 m-2">
               <h3 class="">Add new content:</h3>
              <ul class="list-unstyled list-inline p-0 m-0">
               <li class="list-inline-item p-1">
                 <a class="btn btn-outline-primary text-primary" href="{% url 'course_dashboard:add_content' module.id 'text' %}">Text</a>
               </li>
               <li class="list-inline-item p-1">
                 <a class="btn btn-outline-primary text-primary" href="{% url 'course_dashboard:add_content' module.id 'image' %}">Image</a>
               </li>
               <li class="list-inline-item p-1">
                 <a class="btn btn-outline-primary text-primary" href="{% url 'course_dashboard:add_content' module.id 'video' %}">Video</a>
               </li>
               <li class="list-inline-item p-1">
                 <a class="btn btn-outline-primary text-primary" href="{% url 'course_dashboard:add_content' module.id 'file' %}">File</a>
               </li>
              </ul>
             </div>
           </div>
           <div class="col-md-6">
             <div class="border border-dark shadow rounded p-2 m-2">
               <h3 class="">Add new assessment:</h3>
              <ul class="list-unstyled list-inline p-0 m-0">
               <li class="list-inline-item p-1">
                 <a class="btn btn-outline-primary text-success" href="{% url 'exam_dashboard:add_ca' module.id 'objective' %}">Objective Test</a>
               </li>
               <li class="list-inline-item p-1">
                 <a class="btn btn-outline-primary text-success" href="{% url 'exam_dashboard:add_ca' module.id 'essay' %}">Essay Test</a>
               </li>
               <li class="list-inline-item p-1">
                 <a class="btn btn-outline-primary text-success" href="{% url 'exam_dashboard:add_ca' module.id 'assignment' %}">Assignment</a>
               </li>
              </ul>
             </div>
           </div>
         </div>
       </div>
     </div>
     <div class="row">
       <div class="col-md-6">
         <div class="card card-primary card-outline">
           <div class="card-header">
             <h3 class="card-title">Contents<span class="badge bg-primary">{{ module.num_contents }}</span></h3>
           </div>
           <div class="card-body">
             {% for content in module.contents.all %}
              <div class="border border-primary shadow rounded p-2 m-2">
                {% with item=content.item %}
                   <h4 class="card-subtitle">{{ item }}<span class="badge bg-primary text-sm">{{ item|model_name }}</span></h4>
                   {% if item|model_name == 'file' %}
                    <small class="text-muted">
                      Size: <span class="badge bg-primary text-sm">{{ item.size|filesizeformat }}</span> |
                      Format: <span class="badge bg-primary text-sm">{{ item.format }}</span>
                    </small><br>
                   {% endif %}
                   <span class="text-muted small">Status: 
                    {% if content.live %}
                     <span class="badge bg-success">Live</span>
                     <a href="{% url 'course_dashboard:publish_toggle' 'content' content.pk %}" class="btn btn-primary btn-sm">Unpublish</a>
                    {% else %}
                     <span class="badge bg-info">Draft</span>
                     <a href="{% url 'course_dashboard:publish_toggle' 'content' content.pk %}" class="btn btn-success btn-sm">Publish</a>
                    {% endif %}
                  </span>
                   <a class="btn btn-outline-primary text-primary btn-sm m-1" href="{% url 'course_dashboard:edit_content' module.id item|model_name item.id %}">
                     <i class="fas fa-edit mr-2"></i>Edit</a>
                   <a class="btn btn-outline-primary text-danger btn-sm m-1" href="{% url 'course_dashboard:delete_content' content.id %}">
                     <i class="fas fa-trash mr-2"></i>Delete</a>
                {% endwith %}
              </div>
             {% empty %}
              <p>No content added yet!</p>
             {% endfor %}
           </div>
         </div>
       </div>
       <div class="col-md-6">
         <div class="card card-success card-outline">
           <div class="card-header">
             <h3 class="card-title">Assessments<span class="badge bg-success">{{ module.num_assessments }}</span></h3>
           </div>
           <div class="card-body">
             {% for ca in module.assessments.all %}
              <div class="border border-success shadow rounded p-2 m-2">
                {% with paper=ca.paper %}
                   <h4 class="card-subtitle">{{ paper }} <span class="badge bg-success text-sm">{{ paper|model_name }}</span></h4>
                   Total marks<span class="badge bg-success">{{ paper.total_marks }}</span>
                   Questions<span class="badge bg-success">{{ paper.num_questions }}</span><br>
                   {% if paper|model_name == 'objective' or paper|model_name == 'essay' %}
                    <small class="text-muted">Start: {{ paper.start_time }} - End: {{ paper.end_time }}</small><br>
                   {% endif %}
                   <p class="text-muted small p-0 m-0">Status: 
                    {% if ca.live %}
                     <span class="badge bg-success">Live</span>
                     <a href="{% url 'course_dashboard:publish_toggle' 'ca' ca.pk %}" class="btn btn-primary btn-sm">Unpublish</a>
                    {% else %}
                     <span class="badge bg-info">Draft</span>
                     <a href="{% url 'course_dashboard:publish_toggle' 'ca' ca.pk %}" class="btn btn-success btn-sm">Publish</a>
                    {% endif %}
                    <a href="{% url 'result_dashboard:module_ca_result' module.id ca.id %}" class="btn btn-success btn-sm">
                      <i class="fas fa-check mr-2"></i>Mark results <i class="fas fa-arrow-circle-right"></i>
                    </a>
                  </p>
                   <a class="btn btn-sm btn-outline-success text-success m-1" href="{% url 'exam_dashboard:edit_ca_question' module.id paper|model_name paper.id %}">
                     <i class="fas fa-edit mr-2"></i>Add Question</a>
                   <a class="btn btn-sm btn-outline-success text-success m-1" href="{% url 'exam_dashboard:edit_ca' module.id paper|model_name paper.id %}">
                     <i class="fas fa-edit mr-2"></i>Edit</a>
                   <a class="btn btn-sm btn-outline-success text-danger m-1" href="{% url 'exam_dashboard:delete_ca' ca.id %}">
                     <i class="fas fa-trash mr-2"></i>Delete</a>
                {% endwith %}
              </div>
             {% empty %}
              <p>No assessment added yet!</p>
             {% endfor %}
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>
{% endblock %}

templates/dashboard/course/dashboard.html
{% extends 'teacher_base.html' %}

{% load django_tables2 humanize %}

{% block title %}
Course | Dashboard
{% endblock %}

{% block content %}
 <div class="row">
   {% if user.is_admin %}
   <div class="col-lg-3">
    <hr>
    <a href="{% url 'course_dashboard:add_subject' %}" class="btn btn-primary btn-block mt-2"><i class="fas fa-plus me-3"></i>Add New Subject</a>
    <a href="{% url 'course_dashboard:add_course' %}" class="btn btn-primary btn-block mt-2"><i class="fas fa-plus me-3"></i>Add New Course</a>
   </div>
    <div class="col-lg-9">
      {% render_table table %}
    </div>
    {% endif %}
   <div class="col-12">
     <div class="row  py-5 row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4">
         {% for course in courses %}
         <div class="col">
         <div class="card card-primary card-outline">
           <div class="card-header">
             <h3 class="card-title">{{ course.title }}</h3>
           </div>
           <div class="card-body">
             <table class="table">
               <tr>
                 <td><p class="m-0">Subject</p><span class="badge bg-purple">{{ course.subject }}</span></td>
                 <td>
                   {% if user.is_admin %}
                   <a class="btn btn-app text-info" href="{% url 'course_dashboard:edit_course' course.pk %}"><i class="fas fa-edit"></i>edit</a>
                   <a class="btn btn-app text-danger" href="{% url 'course_dashboard:delete_course' course.pk %}"><i class="fas fa-trash"></i></a>
                   {% endif %}
                 </td>
               </tr>
               <tr>
                 <td>Modules <span class="badge bg-secondary">{{ course.num_modules }}</span></td>
                 <td><a href="{% url 'course_dashboard:edit_module' course.pk %}" class="btn btn-secondary">
                   <i class="fas fa-plus mr-2"></i>Manage Modules</a></td>
               </tr>
               <tr>
                 <td>Students <span class="badge bg-warning">{{ course.num_students }}</span></td>
                 <td><a href="{% url 'exam_dashboard:course_exam' course.pk %}" class="btn btn-primary">
                  <i class="fas fa-bell mr-2"></i>Manage Exams</a></td>
               </tr>
               <tr>
                 <td>Price 
                  {% if course.is_free %}
                   <span class="badge bg-primary">free</span>
                  {% else %}
                   <span class="badge bg-primary">{{ course.price|intcomma }}</span>
                  {% endif %}
                 </td>
                 <td>Certificate 
                  {% if course.is_certificate_free %}
                   <span class="badge bg-warning">free</span>
                  {% else %}
                  <span class="badge bg-warning">{{ course.certificate_price|intcomma }}</span>
                  {% endif %}
                </td>
               </tr>
               <tr>
                <td>
                  Status
                  {% if course.live %}
                   <span class="badge bg-success">Live</span>
                  {% else %}
                  <span class="badge bg-info">Draft</span>
                  {% endif %}
                </td> 
                <td>
                  Registration
                  {% if course.registration_open %}
                   <span class="badge bg-success">Open</span>
                  {% else %}
                   <span class="badge bg-info">Closed</span>
                  {% endif %}
                </td>
               </tr>
             </table>
             <ul class="nav flex-column">
               <li class="nav-item">
                 <p class="nav-link m-0">
                   {{ course.instructor }}<span class="badge bg-primary">instructor</span>
                 </p>
                 <p class="nav-link m-0">
                   Student completed<span class="badge bg-primary">{{ course.num_students_completed }}</span>
                 </p>
                </li>
             </ul>
             {% if user.is_admin %}
             <div class="border rounded border-success m-2 p-2">
               <form class="" action="{% url 'course_dashboard:course_add_student' course.pk %}" method="get">
                 <input type="email" name="student-email" placeholder="Enter email....." class="form-control mb-2">
                 <input type="submit" name="submit" value="Add Student" class="btn btn-success btn-block">
               </form>
             </div>
             {% endif %}
             {% if course.has_modules %}
              <a href="{% url 'course_dashboard:content_list' course.primary_module_id %}" class="btn btn-block btn-primary">
                Manage contents <i class="fas fa-angle-double-right"></i>
              </a>
             {% endif %}
           </div>
         </div>
         </div>
         {% endfor %}
     </div>
   </div>
  </div>
{% endblock %}